### ISSUE TITLE
cephadm: error: unrecognized arguments: --zap-osds

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/cephadm-ansible#14]
Turns out, cephadm-ansible is a bit ahead of Ceph here. If you see this error

```
    usage: cephadm [-h] [--image IMAGE] [--docker] [--data-dir DATA_DIR]
                   [--log-dir LOG_DIR] [--logrotate-dir LOGROTATE_DIR]
                   [--unit-dir UNIT_DIR] [--verbose] [--timeout TIMEOUT]
                   [--retry RETRY] [--env ENV] [--no-container-init]
                   {version,pull,inspect-image,ls,list-networks,adopt,rm-daemon,rm-cluster,run,shell,enter,ceph-volume,unit,logs,bootstrap,deploy,check-host,prepare-host,add-repo,rm-repo,install,registry-login,gather-facts,exporter,host-maintenance,verify-prereqs}
                   ...
    cephadm: error: unrecognized arguments: --zap-osds
```

Simply remove this argument from the playbook, till 16.2.5 is released.

**Comment by guits** [comment]
given only rhcs or dev deployments will have the '--zap-osds' parameter, one option would be to do something like following as a workaround until 16.2.5 is out:

```yaml
    - name: purge ceph cluster
      command: "cephadm rm-cluster --force {{ '' if ceph_origin == 'community' else '--zap-osds' }} --fsid {{ fsid }}"
      when: group_names != ['clients']
```
